from typing import List, Dict, Any

class BaseLLM:
    def load(self) -> None: ...
    def generate(self, context: List[Dict[str, Any]]) -> Dict[str, Any]: ...
    def stream_generate(self, context: List[Dict[str, Any]]): ...
    def count_tokens(self, text: str) -> int: ...
    def healthcheck(self) -> Dict[str, Any]: ...
